version: '2.1'
services: 

 base:
  build: ./base
  image: landscaper_base:latest

 neo4j:
  image: neo4j:3.0
  volumes:
   - /path/to/landscaper/neo4j_data:/data
  ports: 
   - "7474:7474" # expose the port for the console ui
  environment:
   - NEO4J_AUTH=neo4j/password # neo4j requires change from default password, should reflect landscape.cfg
  hostname:
    neo4j

 landscaper:
  build: ./landscaper
  image: landscaper:latest
  volumes:
   - /path/to/landscaper/data:/landscaper/data
   - /path/to/landscaper/landscaper.cfg:/landscaper/landscaper.cfg
  depends_on:
   - neo4j
   - base
  environment:
    - OS_TENANT_NAME=
    - OS_PROJECT_NAME=
    - OS_TENANT_ID=
    - OS_USERNAME=
    - OS_PASSWORD=
    - OS_AUTH_URL=

 web:
  build: ./landscaper_api
  image: landscaper_web:latest
  volumes:
   - /path/to/landscaper/landscaper.cfg:/landscaper/landscaper.cfg
  expose:  
   - "9001"
  ports:
   - "9001:9001"
  depends_on:
   - neo4j
   - landscaper
